# Generated by Django 5.0.4 on 2024-11-11 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Стойноста трябва да бъде от 1 до 5'), django.core.validators.MinValueValidator(1, 'Стойноста трябва да бъде от 1 до 5')]),
        ),
    ]
