# Generated by Django 5.0.4 on 2024-11-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'Името е задължително'}, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'Фамилията е задължителна'}, max_length=50),
        ),
    ]
