# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - BGbattle  

on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - uses: actions/checkout@v4  

      - name: Set up Python version  
        uses: actions/setup-python@v5  
        with:  
          python-version: '3.12'  

      - name: Create and start virtual environment  
        run: |  
          python -m venv venv  
          source venv/bin/activate  
          
      - name: Install pip and setuptools  
        run: |  
          python -m pip install --upgrade pip setuptools  

      - name: Install dependencies  
        run: |  
          source venv/bin/activate  
          pip install -r requirements.txt  
        
      - name: Zip artifact for deployment  
        run: zip release.zip ./* -r  

      - name: Upload artifact for deployment jobs  
        uses: actions/upload-artifact@v4  
        with:  
          name: python-app  
          path: |  
            release.zip  
            !venv/  

  deploy:  
    runs-on: ubuntu-latest  
    needs: build  
    environment:  
      name: 'Production'  
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  
    permissions:  
      id-token: write  # This is required for requesting the JWT  

    steps:  
      - name: Download artifact from build job  
        uses: actions/download-artifact@v4  
        with:  
          name: python-app  

      - name: Unzip artifact for deployment  
        run: unzip release.zip  

      - name: Login to Azure  
        uses: azure/login@v2  
        with:  
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CCE1BABD4B204C6F90A0506306414F58 }}  
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_19B521F82A3644FA8F2D7CB0209DDA35 }}  
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A00548D696604E52A5C0120F4D5BA42F }}  

      - name: 'Deploy to Azure Web App'  
        uses: azure/webapps-deploy@v3  
        id: deploy-to-webapp  
        with:  
          app-name: 'BGbattle'  
          slot-name: 'Production'
          
