# Generated by Django 5.1.3 on 2024-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_alter_battle_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
