# Generated by Django 5.1.3 on 2024-11-29 13:21

import histproject.battles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_alter_battle_name_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='name',
            field=models.CharField(max_length=200, validators=[histproject.battles.validators.clean_bg]),
        ),
    ]
