# Generated by Django 5.1.3 on 2024-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_alter_battle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
